# Generated by Django 3.2.20 on 2023-11-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='testfield',
            field=models.TextField(default='test'),
        ),
    ]
